spring:
  application:
    name: mblog-java
# 数据源配置
  datasource:
    url: jdbc:mysql://localhost:3306/mblog?useSSL=false&serverTimezone=UTC
    username: root
    password: 123qwe
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 20
      minimum-idle: 5
      idle-timeout: 30000
      max-lifetime: 1800000
      connection-timeout: 30000
#  jpa:
#    hibernate:
#      ddl-auto: update
#    show-sql: true
#    properties:
#      hibernate:
#        format_sql: true
# 端口配置
server:
  port: 8081
mybatis-plus:
  mapper-locations: classpath*:/mapper/**/*.xml
#  configuration:
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
